### ISSUE TITLE
question error device or resource busy

### ISSUE THREAD

**Issue by deepch** [blackjack/webcam#19]
os linux all read operation work write return error
fun SetImageFormat

`	err = ioctl.Ioctl(fd, VIDIOC_S_FMT, uintptr(unsafe.Pointer(format)))
`
return error 

Requesting YUV 4:2:2 (YUYV) 1920x1080
2015/11/28 08:58:15 ====> [128 7 0 0 56 4 0 0 89 85 89 86 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
2015/11/28 08:58:15 SetImageFormat return error device or resource busy

**Comment by blackjack** [comment]
It's very hard to tell what's wrong. Does any other webcam software (e.g. cheese) work well on your device?

Does C version of this library work for you? You can checkout commit 2a0ebb51f6ab or tag v0.2 to test it.

**Comment by deepch** [comment]
oh sorry it my fail need kill other pid use device /dev/video0 
if not kill it device read only mode ;(
thx all work sorry..
