### ISSUE TITLE
How to store the data from webcam in a file?

### ISSUE THREAD

**Issue by jabrena** [blackjack/webcam#2]
Hi,

I am a newbie Go developer and I would like to know how to store the picture saved in HDD in a image format as (png/jpg)

Can you help me?

**Comment by blackjack** [comment]
Image in a byte array that is received by webcam.GetImg("/dev/your_webcam") will be in YUV format.
First you have to convert YUV to RGB using formula
   R = Y + 1.140V
   G = Y - 0.395U - 0.581V
   B = Y + 2.032U

And then save the image as JPEG using https://golang.org/pkg/image/jpeg/#Encode

I cannot give you exact code snippet right now, but will try to do it today.

**Comment by blackjack** [comment]
I think you can even define image straight in YUV color mode using https://golang.org/src/image/color/ycbcr.go?s=2328:2366#L72

**Comment by jabrena** [comment]
Hi @blackjack Many thanks for the support. I will try to implement this way.

**Comment by blackjack** [comment]
I just want to state that this library in current state is not really suitable to reliably work with webcam (better way is maybe use OpenCL bindings for that. But since it looks like it's pretty popular already (21 star on github already) I maybe will have to prettify it :)

**Comment by jabrena** [comment]
Hi @blackjack yes, besides, I found another "sugar" of your idea in another repo.
Many thanks for the support.

**Comment by mdlayher** [comment]
Hi @blackjack , very cool library.  I too am looking for a way to spit out a single JPEG image from a webcam.

I've tried reading a single frame and attempting to write it out as a JPEG image, but I keep running into a variety of errors.  Is there a simple way to make this work?

Thanks for your time.

**Comment by blackjack** [comment]
@mdlayher did you set camera format to JPEG (https://godoc.org/github.com/blackjack/webcam#Webcam.SetImageFormat)?

**Comment by blackjack** [comment]
Oops, sorry, I didn't understand you correctly. 
So first, you have to look at the formats your webcam supports.
If there's MJPEG format, grab a frame from camera and just save it - it should be a valid JPEG image. Otherwise you have to convert received frame to JPEG by yourself.
