### ISSUE TITLE
USING IT FOR RPI CAMERA?

### ISSUE THREAD

**Issue by saurabh98s** [blackjack/webcam#25]
how can i use it for the rpi camera?
when i tried to run it on my raspberry pi it gave me error :
10:13 Unable to open webcam no such file or directory
Can you suggest a way?

**Comment by blackjack** [comment]
You need to provide correct path to webcam device (e.g. /dev/video0). To get list of camera devices on your host you can install ```v4l-utils``` package and run  ```v4l2-ctl --list-devices```.
