### ISSUE TITLE
Bad interaction with SDL RenderPresent?

### ISSUE THREAD

**Issue by cmatsuoka** [blackjack/webcam#5]
I'm experiencing a rather strange problem related to v4l2 frame reading: whenever `ReadFrame()` is called (or, more, precisely, the buffer enqueuing/dequeuing ioctls), SDL screen updates stop or happen at random, large intervals. I don't know if the problem is in V4L2, SDL, the GL stack, X11,  drm, or my code. I still didn't try to reimplement the example in C to bypass the Go packages, but it doesn't seem that Go is causing this.

Perhaps you could try the following example to see if you have any idea on what's happening? This code should show a smooth color change in the SDL window, but fails to do so if `cam.ReadFrame()` is uncommented. The frame counter shows that `ReadFrame()` is not blocking, it's just the window image that's not being properly updated.

    package main

    import (
    	"fmt"
    	"github.com/blackjack/webcam"
    	"github.com/veandco/go-sdl2/sdl"
    	"os"    
    )
    
    func main() {
    	window, err := sdl.CreateWindow("test", sdl.WINDOWPOS_UNDEFINED,
    		sdl.WINDOWPOS_UNDEFINED, 640, 480, sdl.WINDOW_SHOWN)
    	if err != nil {
    		fmt.Printf("can't create window: %s\n", err)
    		os.Exit(1)
    	}
    	defer window.Destroy()
    
    	renderer, err := sdl.CreateRenderer(window, -1, sdl.RENDERER_ACCELERATED)
    	if err != nil {
    		fmt.Printf("can't create renderer: %s\n", err)
    		os.Exit(1)
    	}
    	defer renderer.Destroy()
    
    	texture, err := renderer.CreateTexture(sdl.PIXELFORMAT_YUY2, sdl.TEXTUREACCESS_STREAMING, 640, 480)
    	if err != nil {
    		fmt.Printf("can't create texture: %s", err)
    		os.Exit(1)
    	}
    	defer texture.Destroy()
    
    	x := uint8(0)
    
    	cam, err := webcam.Open("/dev/video0")
    	if err != nil {
    		fmt.Printf("can't open webcam: %s", err)
    		os.Exit(1)
    	}
    	_, _, _, err = cam.SetImageFormat(0x56595559, 640, 480)
    	if err != nil {
    		fmt.Printf("can't set image format: %s", err)
    		os.Exit(1)
    	}
    	cam.StartStreaming()
    
    	for {
    		cam.WaitForFrame(1)
    		cam.ReadFrame()
    		renderer.SetDrawColor(x, x, x, 255)
    		x++
    		renderer.Clear()
    		renderer.Present()
    		fmt.Printf("%03d\r", x)
    	}
    }

**Comment by blackjack** [comment]
Hi, @cmatsuoka.
I think the problem is in the way Go interracts with C libraries. Look at [this](https://www.cockroachlabs.com/blog/the-cost-and-complexity-of-cgo/) article, for example.

There is a pull request I'm currently working on (#4) that should fix your problem. Unfortunately now it's under development because of issues that popped up during testing, but I've checked your example and it runs smoothly on my machine. 

Have a look at **goimpl** branch of library and see if it helps you.

**Comment by cmatsuoka** [comment]
Hi @blackjack, I tried the goimpl branch and it indeed fixes the screen update rates and makes the example above run smoothly. It doesn't work completely because if I add the code to actually show the captured frame it seems that `ReadFrame()` is always returning the same buffer. The index variable is being correctly updated from 0 to 31, but the buffer contents change only after a full index cycle. Maybe a  queuing problem? Perhaps this is already in your radar, otherwise I can investigate further.

**Comment by cmatsuoka** [comment]
Confirmed: buffer sequence numbers are correct, pointers to frame data are different, but image data is the same for all buffers.

**Comment by blackjack** [comment]
I've fixed buffer reading in 008c830212ab0c5c24db0a7f887b08477bc77832, can you test it now?

**Comment by cmatsuoka** [comment]
Problem fixed, frames are being correctly updated. Thanks!

**Comment by blackjack** [comment]
Good to hear that
