### ISSUE TITLE
Could this master version release?

### ISSUE THREAD

**Issue by LiangChenYue** [blackjack/webcam#64]
Some method didn't implement on the latest released version but master version. Could it be released ?

**Comment by edaniels** [comment]
Which method?

**Comment by LiangChenYue** [comment]
1.
// GetName returns the human-readable name of the device
func (w *Webcam) GetName() (string, error) {
	return getName(w.fd)
}

2.
// Sets automatic white balance correction
func (w *Webcam) SetAutoWhiteBalance(val bool) error {
	v := int32(0)
	if val {
		v = 1
	}
	return setControl(w.fd, V4L2_CID_AUTO_WHITE_BALANCE, v)
}

**Comment by edaniels** [comment]
@LiangChenYue done with https://github.com/blackjack/webcam/releases/tag/v0.4!

**Comment by LiangChenYue** [comment]
Thank you so much. <(_ _)>

**Comment by edaniels** [comment]
Absolutely :)
