### ISSUE TITLE
Request to cut a new release to include fd leak fix

### ISSUE THREAD

**Issue by seanavery** [blackjack/webcam#68]
Ran into an issue recently with file descriptors piling up on Raspberry PI devices which include v4l2 files that do not satisfy the capabilities check. This issue has already been fixed in the master branch -- thanks @bpstark!

@edaniels Since this is a somewhat critical issue, I am wondering if we could cut a new release to include this fix.

**Comment by edaniels** [comment]
Done in v0.6.0!
